language: julia

os:
    - linux

julia:
    - 0.6
    - 0.7
    - 1.0
    - nightly

#matrix:
#    allow_failures:
#        - julia: nightly

after_success:
    - julia -e 'cd(Pkg.dir("PDEAssembler")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
